FROM debian
ENV TERM=xterm-256color \
    PATH=/home/debian/.local/bin:/etc/toolbox/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    TOOLBOX_RUN_ONCE=1 \
    TOOLBOX_RUN_PER_STARTUP=1

# RUN rm /etc/apt/sources.list && \
#     rm /etc/apt/sources.list.d/ubuntu.sources && \
#     echo "deb $APT_MIRROR noble main restricted universe multiverse" >> /etc/apt/sources.list && \
#     echo "deb $APT_MIRROR noble-updates main restricted universe multiverse" >> /etc/apt/sources.list && \
#     echo "deb $APT_MIRROR noble-backports main restricted universe multiverse" >> /etc/apt/sources.list && \
#     echo "deb $APT_SECURE noble-security main restricted universe multiverse" >> /etc/apt/sources.list && \
#     apt update && apt upgrade -y

RUN apt update && apt install -y libgl1 sudo gosu curl wget nano vim git python3-venv python3-pip xz-utils openssh-server supervisor && apt clean && rm -rf /var/lib/apt/lists/* && \
    mkdir -p /run/sshd && rm /etc/ssh/ssh_host_* && \
    useradd -m -G sudo -s /bin/bash debian && \
    echo "debian:debian" | chpasswd && mkdir -p /var/log/supervisor && \
    mkdir -p /etc/toolbox/scripts/run-once && mkdir -p /etc/toolbox/scripts/per-startup && mkdir -p /etc/toolbox/scripts/misc && mkdir -p /etc/toolbox/local/bin && touch /etc/toolbox/.env
RUN cd / && wget https://mirrors.aliyun.com/nodejs-release/v22.16.0/node-v22.16.0-linux-x64.tar.xz && \
    tar xvf node-v22.16.0-linux-x64.tar.xz && cp -r node-v22.16.0-linux-x64/* /etc/toolbox/local && rm -rf node-v22.16.0-linux-x64 && rm node-v22.16.0-linux-x64.tar.xz && \
    node -v && npm -v 
#    npm config set registry https://registry.npmmirror.com
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /etc/toolbox/local/bin
COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY conf.d /etc/supervisor/conf.d
COPY entrypoint.sh /etc/toolbox/entrypoint.sh
COPY 00-openssh.sh /etc/toolbox/scripts/run-once/00-openssh.sh
STOPSIGNAL SIGINT
CMD ["/bin/bash","/etc/toolbox/entrypoint.sh"]
