[program:code-server]
command=gosu ubuntu:ubuntu /bin/bash -c "/home/ubuntu/.codesvr/bin/code-server"
directory=/home/ubuntu/workdir
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/code-server.log
stderr_logfile=/var/log/supervisor/code-server_err.log