[program:jupyterlab]
command=gosu ubuntu:ubuntu /bin/bash -c "jupyter-lab -y --no-browser --ip=0.0.0.0 --port=8000"
directory=/home/ubuntu/workdir
user=root
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/jupyterlab.log
stderr_logfile=/var/log/supervisor/jupyterlab_err.log